SET NAMES utf8mb4;

ALTER TABLE world_post
    ADD COLUMN media_type VARCHAR(20) NOT NULL DEFAULT 'TEXT' COMMENT 'TEXT/IMAGE/VIDEO' AFTER content,
    ADD COLUMN image_url VARCHAR(1024) NULL COMMENT '图片URL' AFTER media_type,
    ADD COLUMN video_url VARCHAR(1024) NULL COMMENT '视频URL' AFTER image_url;
