/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/auth/login" |
       "/pages/auth/register" |
       "/pages/chat/chat-list" |
       "/pages/chat/chat-room" |
       "/pages/contact/contact-detail" |
       "/pages/contact/contact-list" |
       "/pages/profile/profile" |
       "/pages/project/project" |
       "/pages/world/world" |
       "/pages/project/components/ProjectDetailView" |
       "/pages/project/components/ProjectListView" |
       "/pages/project/components/ProjectSidebarDrawer" |
       "/pages/project/components/modals/CreateProjectModal" |
       "/pages/project/components/modals/ShareProjectModal" |
       "/pages/project/components/modals/TransferOwnershipModal" |
       "/pages/project/components/modals/UpdateBidModal";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/chat/chat-list" | "/pages/project/project" | "/pages/world/world" | "/pages/contact/contact-list" | "/pages/profile/profile"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
