ALTER TABLE credit_record
  MODIFY subject_type VARCHAR(20) NOT NULL COMMENT 'HUMAN/AGENT/SYSTEM';

ALTER TABLE violation_record
  MODIFY subject_type VARCHAR(20) NOT NULL COMMENT 'HUMAN/AGENT/SYSTEM';
